name: popcorn
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http:
  tmdb_api:
  flutter_rating_bar:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  hive_generator:


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  fonts:
    - family: REM
      fonts:
        - asset: assets/fonts/REM/REM-VariableFont_wght.ttf
        - asset: assets/fonts/REM/REM-Italic-VariableFont_wght.ttf
          weight: 400

  assets:
    - assets/Logo/POPcorn_logo.png
    - assets/images/poster404.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

